%    This file is part of TFMLAB.
%     Copyright (C) 2020 MAtrix
%     Copyright (C) 2020 Bme, Dep. Mech. Engineering, KUleuven (Belgium)
%     Copyright (C) 2020 Esc. Téc. Sup. de Ingeniería, Universidad de Sevilla (Spain)
%
%     This library is free software: you can redistribute it and/or modify
%     it under the terms of the GNU Lesser General Public License as published
%     by the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
%     This software is provided "as is",
%     but WITHOUT ANY WARRANTY; without even the implied warranty of
%     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%     GNU Lesser General Public License for more details
%     <http://www.gnu.org/licenses/>.

function runFFresultFile(tools_freefem_folder_name,write_options,file_name,result_folders,code_names,mech_props,extension)

% command_line = [code_names.external filesep 'FreeFem++' filesep ...
%     'FreeFem++ ' [tools_freefem_folder_name filesep 'principals.edp'] ...
%     ' -mesh ' [write_options.write_path filesep file_name(1:end-4) '_mesh.msh']...
%     ' -u1 ' [write_options.write_path filesep 'u1_' extension '.sol']...
%     ' -u2 ' [write_options.write_path filesep 'u2_' extension '.sol']...
%     ' -u3 ' [write_options.write_path filesep 'u3_' extension '.sol']...
%     ' -outdirdisp ' [result_folders.freefem_results_folder filesep 'disp_' extension '.vtu']...
%     ' -outdirstrainsp ' [result_folders.freefem_results_folder filesep 'strainsp_' extension '.txt']...
%     ' -outdirstresses ' [result_folders.freefem_results_folder filesep 'stresses_' extension '.txt']...
%     ' -outdirstressesp ' [result_folders.freefem_results_folder filesep 'stressesp_' extension '.txt']...
%     ' -outdirstrains ' [result_folders.freefem_results_folder filesep 'strains_' extension '.txt']...
%     ' -outdirvtk ' [result_folders.freefem_results_folder filesep 'principal_' extension '.vtu']...
%     ' -writedisp 0'...
%     ' -writevtk 1'...
%     ' -ngel 2'...
%     ' -ncell 1'...
%     ' -egel ' num2str(mech_props.elastic_modulus) ...
%     ' -nugel ' num2str(mech_props.poissons_ratio) ...
%     ' -v 0'];

command_line = [ ...
    'FreeFem++ ' [tools_freefem_folder_name filesep 'principals.edp'] ...
    ' -mesh ' [write_options.write_path filesep file_name(1:end-4) '_mesh.msh']...
    ' -u1 ' [write_options.write_path filesep 'u1_' extension '.sol']...
    ' -u2 ' [write_options.write_path filesep 'u2_' extension '.sol']...
    ' -u3 ' [write_options.write_path filesep 'u3_' extension '.sol']...
    ' -outdirdisp ' [result_folders.freefem_results_folder filesep 'disp_' extension '.vtu']...
    ' -outdirstrainsp ' [result_folders.freefem_results_folder filesep 'strainsp_' extension '.txt']...
    ' -outdirstresses ' [result_folders.freefem_results_folder filesep 'stresses_' extension '.txt']...
    ' -outdirstressesp ' [result_folders.freefem_results_folder filesep 'stressesp_' extension '.txt']...
    ' -outdirstrains ' [result_folders.freefem_results_folder filesep 'strains_' extension '.txt']...
    ' -outdirvtk ' [result_folders.freefem_results_folder filesep 'principal_' extension '.vtu']...
    ' -writedisp 0'...
    ' -writevtk 1'...
    ' -ngel 2'...
    ' -ncell 1'...
    ' -egel ' num2str(mech_props.elastic_modulus) ...
    ' -nugel ' num2str(mech_props.poissons_ratio) ...
    ' -v 0'];


status = system(command_line);